# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/zynq_blk_smartconnect_0_0.xci
# IP: The module: 'zynq_blk_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/bd_39ac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_0/bd_39ac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_1/bd_39ac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_2/bd_39ac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_3/bd_39ac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_4/bd_39ac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_5/bd_39ac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_6/bd_39ac_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_7/bd_39ac_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_8/bd_39ac_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_9/bd_39ac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_10/bd_39ac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_blk_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_1/bd_39ac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_1/bd_39ac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_5/bd_39ac_s00a2s_0_ooc.xdc

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_6/bd_39ac_sawn_0_ooc.xdc

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_7/bd_39ac_swn_0_ooc.xdc

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_8/bd_39ac_sbn_0_ooc.xdc

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_9/bd_39ac_m00s2a_0_ooc.xdc

# IP: D:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/zynq_blk_smartconnect_0_0.xci
# IP: The module: 'zynq_blk_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/bd_39ac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_0/bd_39ac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_1/bd_39ac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_2/bd_39ac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_3/bd_39ac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_4/bd_39ac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_5/bd_39ac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_6/bd_39ac_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_7/bd_39ac_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_8/bd_39ac_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_9/bd_39ac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_10/bd_39ac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_blk_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_1/bd_39ac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_1/bd_39ac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_5/bd_39ac_s00a2s_0_ooc.xdc

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_6/bd_39ac_sawn_0_ooc.xdc

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_7/bd_39ac_swn_0_ooc.xdc

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_8/bd_39ac_sbn_0_ooc.xdc

# XDC: d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_9/bd_39ac_m00s2a_0_ooc.xdc
