# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/zynq_tdc/tdc_ip_prj/tdc_ip_prj.cache/wt [current_project]
set_property parent.project_path D:/zynq_tdc/tdc_ip_prj/tdc_ip_prj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/zynq_tdc/tdc_ip_prj/tdc_ip_prj.srcs [current_project]
update_ip_catalog
set_property ip_output_repo d:/zynq_tdc/tdc_ip_prj/tdc_ip_prj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/zynq_tdc/tdc_ip_prj/tdc_ip_prj.srcs/MyPkg.vhd
  D:/zynq_tdc/tdc_ip_prj/tdc_ip_prj.srcs/risingEdgeDetector.vhd
  D:/zynq_tdc/tdc_ip_prj/tdc_ip_prj.srcs/delayLine.vhd
  D:/zynq_tdc/tdc_ip_prj/tdc_ip_prj.srcs/adderTreeLegacy.vhd
  D:/zynq_tdc/tdc_ip_prj/tdc_ip_prj.srcs/encoder.vhd
  D:/zynq_tdc/tdc_ip_prj/tdc_ip_prj.srcs/counter.vhd
  D:/zynq_tdc/tdc_ip_prj/tdc_ip_prj.srcs/TDCchannel.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TDCchannel -part xc7z020clg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TDCchannel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TDCchannel_utilization_synth.rpt -pb TDCchannel_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
