# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/tdc.xdc

# Block Designs: bd/zynq_blk/zynq_blk.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk || ORIG_REF_NAME==zynq_blk} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_processing_system7_0_0/zynq_blk_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_processing_system7_0_0 || ORIG_REF_NAME==zynq_blk_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_axis_data_fifo_0_0/zynq_blk_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_axis_data_fifo_0_0 || ORIG_REF_NAME==zynq_blk_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_axi_dma_0_0/zynq_blk_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_axi_dma_0_0 || ORIG_REF_NAME==zynq_blk_axi_dma_0_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/zynq_blk_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_smartconnect_0_0 || ORIG_REF_NAME==zynq_blk_smartconnect_0_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_rst_ps7_0_100M_1_0/zynq_blk_rst_ps7_0_100M_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_rst_ps7_0_100M_1_0 || ORIG_REF_NAME==zynq_blk_rst_ps7_0_100M_1_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_ps7_0_axi_periph_2/zynq_blk_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_ps7_0_axi_periph_2 || ORIG_REF_NAME==zynq_blk_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_clk_wiz_0_0/zynq_blk_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_clk_wiz_0_0 || ORIG_REF_NAME==zynq_blk_clk_wiz_0_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_TDCchannel_0_0/zynq_blk_TDCchannel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_TDCchannel_0_0 || ORIG_REF_NAME==zynq_blk_TDCchannel_0_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_TDCchannel_1_0/zynq_blk_TDCchannel_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_TDCchannel_1_0 || ORIG_REF_NAME==zynq_blk_TDCchannel_1_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_xbar_0/zynq_blk_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_xbar_0 || ORIG_REF_NAME==zynq_blk_xbar_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_axi_gpio_0_0/zynq_blk_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_axi_gpio_0_0 || ORIG_REF_NAME==zynq_blk_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_tdc_ctl_fromps_0_1/zynq_blk_tdc_ctl_fromps_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_tdc_ctl_fromps_0_1 || ORIG_REF_NAME==zynq_blk_tdc_ctl_fromps_0_1} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_proc_rst_clk2_0/zynq_blk_proc_rst_clk2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_proc_rst_clk2_0 || ORIG_REF_NAME==zynq_blk_proc_rst_clk2_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_tdc_control_0_0/zynq_blk_tdc_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_tdc_control_0_0 || ORIG_REF_NAME==zynq_blk_tdc_control_0_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_clk_wiz_1_0/zynq_blk_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_clk_wiz_1_0 || ORIG_REF_NAME==zynq_blk_clk_wiz_1_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_hit_src_chg_0_0/zynq_blk_hit_src_chg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_hit_src_chg_0_0 || ORIG_REF_NAME==zynq_blk_hit_src_chg_0_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_hit_src_chg_1_0/zynq_blk_hit_src_chg_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_hit_src_chg_1_0 || ORIG_REF_NAME==zynq_blk_hit_src_chg_1_0} -quiet] -quiet

# IP: bd/zynq_blk/ip/zynq_blk_auto_pc_0/zynq_blk_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_blk_auto_pc_0 || ORIG_REF_NAME==zynq_blk_auto_pc_0} -quiet] -quiet

# XDC: bd/zynq_blk/zynq_blk_ooc.xdc
