# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/zynq_tdc/tdc_system_prj/tdc_system_prj.cache/wt [current_project]
set_property parent.project_path D:/zynq_tdc/tdc_system_prj/tdc_system_prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib work [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/zynq_tdc/tdc_ip_prj [current_project]
update_ip_catalog
set_property ip_output_repo d:/zynq_tdc/tdc_system_prj/tdc_system_prj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog D:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/hdl/zynq_blk_wrapper.v
add_files D:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/zynq_blk.bd
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_processing_system7_0_0/zynq_blk_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_axis_data_fifo_0_0/zynq_blk_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_axi_dma_0_0/zynq_blk_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_axi_dma_0_0/zynq_blk_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_axi_dma_0_0/zynq_blk_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_1/bd_39ac_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_1/bd_39ac_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_5/bd_39ac_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_6/bd_39ac_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_7/bd_39ac_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_8/bd_39ac_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_smartconnect_0_0/bd_0/ip/ip_9/bd_39ac_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_rst_ps7_0_100M_1_0/zynq_blk_rst_ps7_0_100M_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_rst_ps7_0_100M_1_0/zynq_blk_rst_ps7_0_100M_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_rst_ps7_0_100M_1_0/zynq_blk_rst_ps7_0_100M_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_clk_wiz_0_0/zynq_blk_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_clk_wiz_0_0/zynq_blk_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_clk_wiz_0_0/zynq_blk_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_xbar_0/zynq_blk_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_axi_gpio_0_0/zynq_blk_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_axi_gpio_0_0/zynq_blk_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_axi_gpio_0_0/zynq_blk_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_proc_rst_clk2_0/zynq_blk_proc_rst_clk2_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_proc_rst_clk2_0/zynq_blk_proc_rst_clk2_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_proc_rst_clk2_0/zynq_blk_proc_rst_clk2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_clk_wiz_1_0/zynq_blk_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_clk_wiz_1_0/zynq_blk_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_clk_wiz_1_0/zynq_blk_clk_wiz_1_0_late.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_clk_wiz_1_0/zynq_blk_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/ip/zynq_blk_auto_pc_0/zynq_blk_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/sources_1/bd/zynq_blk/zynq_blk_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/constrs_1/new/tdc.xdc
set_property used_in_implementation false [get_files D:/zynq_tdc/tdc_system_prj/tdc_system_prj.srcs/constrs_1/new/tdc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top zynq_blk_wrapper -part xc7z020clg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zynq_blk_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zynq_blk_wrapper_utilization_synth.rpt -pb zynq_blk_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
